# Generated by Django 5.0.1 on 2024-01-08 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrashion',
            name='number',
            field=models.IntegerField(verbose_name=15),
        ),
    ]
